SNP-271 fix: stop listener
surfstudio/flutter-otp-autofill pull request #49
Opened 2023-03-02 14:25 UTC by mark-kascheev

## Related tasks
![BUG](https://github.com/surfstudio/flutter-otp-autofill/issues/38)

## Changes
Missing call of ```unRegisterBroadcastReceivers()```

## Checklist for self-check
- [x] Commits and PRs have been filed according to [the rules on the project](https://github.com/surfstudio/surf-flutter-app-template#workflow-in-a-repository).
- [x] The author is marked as an assigne and assigned mandatory reviewers.
- [x] Required labels marked
- [x] Specified related tasks and/or related PRs.
- [x] Specified Changes.
- [ ] Attached videos/screenshots demonstrating the fix/feature.
- [x] All unspecified fields in the PR description deleted.
- [ ] New code covered by tests.

## Checklist for reviewers
- [ ] CI passed successfully _(with a green check mark)_.
- [ ] PR is atomic, by volume no more than 400 (+-) corrected lines (not including codogen).

Design:
- [ ] System design corresponds to the agreements on structure and architecture on the project.
- [ ] The code is decomposed into necessary and sufficient components.

Functionality:
- [ ] The code solves the problem.
- [ ] Any changes to the user interface are reasonable and look good.

Complexity:
- [ ] The code is clear, easy to read, functions are small, no more than 50 lines.
- [ ] The logic is not overcomplicated, there is no overengineering (no code sections that may be needed in the future, but no one knows about it).

Tests:
- [ ] Updated or added tests for mandatory components.
- [ ] The tests are correct, helpful, and well designed/developed.

Naming:
- [ ] The naming of variables, methods, classes and other components is understandable.

Comments:
- [ ] The comments are understandable and helpful.

Documentation:
- [ ] All labels are correct
- [ ] Technical documentation updated (after approval, updates last reviewer).

2023-03-09 07:17 UTC, dshevchenkoo commented on .fvm/flutter_sdk
> +/Users/parshonok/fvm/versions/3.7.6
add to gitignore

2023-03-09 07:18 UTC, dshevchenkoo commented on android/src/main/kotlin/ru/surfstudio/otp_autofill/OTPPlugin.kt
> +        unRegisterBroadcastReceivers()
add comment

2023-07-12 08:40 UTC, mpkander requested changes

2023-07-12 08:40 UTC, mpkander commented on example/.fvm/flutter_sdk
> +/Users/parshonok/fvm/versions/3.7.6
You also need to delete the file

2023-07-12 08:40 UTC, mpkander commented on pubspec.yaml
> +  sdk: ">=2.18.0 <3.0.0"
Is it necessary to upgrade SDK?

2023-07-12 09:23 UTC, plasticfiresam commented on pubspec.yaml
> +  sdk: ">=2.18.0 <3.0.0"
Nope, fixed

2023-07-12 09:23 UTC, plasticfiresam commented on example/.fvm/flutter_sdk
> +/Users/parshonok/fvm/versions/3.7.6
Deleted

2023-07-12 09:25 UTC, maxim-sysoev approved these changes

2023-07-12 09:29 UTC, mpkander approved these changes
LGTM

2023-07-12 10:25 UTC, merged