Fixed #55 Upgraded Kotlin version
surfstudio/flutter-otp-autofill pull request #56
Opened 2023-06-26 12:57 UTC by AgnelSelvan

## Related tasks
Depends on Issue #55 

## Changes
Updated Kotlin version from ```ext.kotlin_version = '1.3.50'``` to ```ext.kotlin_version = '1.7.10'```

## Checklist for self-check
- [x] Commits and PRs have been filed according to [the rules on the project](https://github.com/surfstudio/surf-flutter-app-template#workflow-in-a-repository).
- [ ] The author is marked as an assigne and assigned mandatory reviewers.
- [x] Required labels marked
- [x] Specified related tasks and/or related PRs.
- [x] Specified Changes.
- [ ] Attached videos/screenshots demonstrating the fix/feature.
- [x] All unspecified fields in the PR description deleted.
- [ ] New code covered by tests.

## Checklist for reviewers
- [ ] CI passed successfully _(with a green check mark)_.
- [ ] PR is atomic, by volume no more than 400 (+-) corrected lines (not including codogen).

Design:
- [ ] System design corresponds to the agreements on structure and architecture on the project.
- [ ] The code is decomposed into necessary and sufficient components.

Functionality:
- [x] The code solves the problem.
- [x] Any changes to the user interface are reasonable and look good.

Complexity:
- [x] The code is clear, easy to read, functions are small, no more than 50 lines.
- [x] The logic is not overcomplicated, there is no overengineering (no code sections that may be needed in the future, but no one knows about it).

Tests:
- [ ] Updated or added tests for mandatory components.
- [ ] The tests are correct, helpful, and well designed/developed.

Naming:
- [x] The naming of variables, methods, classes and other components is understandable.

Comments:
- [x] The comments are understandable and helpful.

Documentation:
- [x] All labels are correct
- [ ] Technical documentation updated (after approval, updates last reviewer).

2023-07-03 17:00 UTC, tinted-knight requested changes

2023-07-04 15:26 UTC, AgnelSelvan commented on android/build.gradle
> +    ext.kotlin_version = '1.7.10'
Hey @tinted-knight , 
Sure, will try to update it to the latest AGP version as well as the Kotlin version once it is tested.

2023-07-04 20:40 UTC, tinted-knight commented on android/build.gradle
> +    ext.kotlin_version = '1.7.10'
Great, thank you. Feel free to ping me if you have any problems.

2023-07-05 09:56 UTC, AgnelSelvan commented
Hey @tinted-knight  ,
AGP version updated to the latest version but Kotlin version I tried updating to 1.8.22 the issue I faced is to update the example project as well to the latest 1.8 Kotlin version. If the user is using some old version of Kotlin then the user will be forced to update the Kotlin version to 1.8 as in 1.7.21 it's not the case.
So keeping the Kotlin version as 1.7.21, which is common Flutter's latest new project's Kotlin version of Android.

2023-07-10 10:10 UTC, plasticfiresam approved these changes

2023-07-11 09:14 UTC, closed without merging